### ISSUE TITLE
missing ops

### ISSUE THREAD

**Issue by flynnamy** [Vicky0522/RSFNet#2]
Hi, it missing rgb2lab_func from basicsr.ops.color. I check that basicsr repo does not include this op. Could you please share the color op.Thanks! @Vicky0522

**Comment by Vicky0522** [comment]
Sorry for this mistake. I have just removed the `basicsr/ops` from the .gitignore file. Now the ops files are added.

**Comment by dawnlh** [comment]
@Vicky0522 Could you please provide some instructions on compiling the ops. I tried to build it with`python setup.py build_ext` or `python setup.py install`, and the output showed the build was successful. But when I ran the test code, it still failed with an error "No module named cudaops_color".

**Comment by Vicky0522** [comment]
> @Vicky0522 Could you please provide some instructions on compiling the ops. I tried to build it with`python setup.py build_ext` or `python setup.py install`, and the output showed the build was successful. But when I ran the test code, it still failed with an error "No module named cudaops_color".

Have you tried running `python setup.py develop`? The CUDA extension is implemented using JIT compilation, which compiles simultaneously during testing time after the environment setup. For more details, you can refer to the [JIT Compiling Extensions guide](https://pytorch.org/tutorials/advanced/cpp_extension.html#jit-compiling-extensions) from PyTorch.

If you continue to encounter issues, please share the error log, and I'll help investigate further.

**Comment by dawnlh** [comment]
@Vicky0522 So you mean I only need to run `python setup.py develop` in the root dir to build the basicsr package, and there is no need to build ops separately? I did in this way, and there is the output log:

```
(bsr_rsf) >python setup.py develop 
running develop
C:\ProgramData\miniforge3\envs\bsr_rsf\lib\site-packages\setuptools\command\develop.py:41: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  easy_install.initialize_options(self)
C:\ProgramData\miniforge3\envs\bsr_rsf\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
running egg_info
writing basicsr.egg-info\PKG-INFO
writing dependency_links to basicsr.egg-info\dependency_links.txt
writing entry points to basicsr.egg-info\entry_points.txt
writing requirements to basicsr.egg-info\requires.txt
writing top-level names to basicsr.egg-info\top_level.txt
reading manifest file 'basicsr.egg-info\SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'basicsr.egg-info\SOURCES.txt'
running build_ext
Creating c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages\basicsr.egg-link (link to .)
Removing basicsr 1.2.0+63d5ab0 from easy-install.pth file
basicsr 1.3.5 is already the active version in easy-install.pth
detected new path 'f:\\project\\styletransfer\\code\\nafnet'
Installing pyinstrument-script.py script to C:\ProgramData\miniforge3\envs\bsr_rsf\Scripts
Installing pyinstrument.exe script to C:\ProgramData\miniforge3\envs\bsr_rsf\Scripts

Installed f:\project\styletransfer\code\attempt\rsfnet
Processing dependencies for basicsr==1.3.5
Searching for tensorboard==2.18.0
Best match: tensorboard 2.18.0
Adding tensorboard 2.18.0 to easy-install.pth file
Installing tensorboard-script.py script to C:\ProgramData\miniforge3\envs\bsr_rsf\Scripts
Installing tensorboard.exe script to C:\ProgramData\miniforge3\envs\bsr_rsf\Scripts

Using c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages
Searching for werkzeug==3.0.6
Best match: werkzeug 3.0.6
Adding werkzeug 3.0.6 to easy-install.pth file

Using c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages
Searching for tensorboard-data-server==0.7.2
Best match: tensorboard-data-server 0.7.2
Adding tensorboard-data-server 0.7.2 to easy-install.pth file

Using c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages
Searching for six==1.16.0
Best match: six 1.16.0
Adding six 1.16.0 to easy-install.pth file

Using c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages
Searching for setuptools==75.3.0
Best match: setuptools 75.3.0
Adding setuptools 75.3.0 to easy-install.pth file

Using c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages
Searching for protobuf==4.25.5
Best match: protobuf 4.25.5
Adding protobuf 4.25.5 to easy-install.pth file

Using c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages
Searching for packaging==24.1
Best match: packaging 24.1
Adding packaging 24.1 to easy-install.pth file

Using c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages\setuptools\_vendor
Searching for numpy==1.26.0
Best match: numpy 1.26.0
Adding numpy 1.26.0 to easy-install.pth file
Installing f2py-script.py script to C:\ProgramData\miniforge3\envs\bsr_rsf\Scripts
Installing f2py.exe script to C:\ProgramData\miniforge3\envs\bsr_rsf\Scripts

Using c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages
Searching for Markdown==3.7
Best match: Markdown 3.7
Adding Markdown 3.7 to easy-install.pth file
Installing markdown_py-script.py script to C:\ProgramData\miniforge3\envs\bsr_rsf\Scripts
Installing markdown_py.exe script to C:\ProgramData\miniforge3\envs\bsr_rsf\Scripts

Using c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages
Searching for grpcio==1.67.1
Best match: grpcio 1.67.1
Adding grpcio 1.67.1 to easy-install.pth file

Using c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages
Searching for absl-py==2.1.0
Best match: absl-py 2.1.0
Adding absl-py 2.1.0 to easy-install.pth file

Using c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages
Searching for MarkupSafe==3.0.2
Best match: MarkupSafe 3.0.2
Adding MarkupSafe 3.0.2 to easy-install.pth file

Using c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages
Searching for importlib-metadata==8.5.0
Best match: importlib-metadata 8.5.0
Adding importlib-metadata 8.5.0 to easy-install.pth file

Using c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages
Searching for zipp==3.20.2
Best match: zipp 3.20.2
Adding zipp 3.20.2 to easy-install.pth file

Using c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages
Finished processing dependencies for basicsr==1.3.5
```
Then, I run the test code:

```
>python basicsr/test.py -opt test_rsfnet_map_fivek_zas.yml
Using C:\Users\mmm\AppData\Local\torch_extensions\torch_extensions\Cache\py39_cu113 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file C:\Users\mmm\AppData\Local\torch_extensions\torch_extensions\Cache\py39_cu113\cudaops_color\build.ninja...
Building extension module cudaops_color...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
Traceback (most recent call last):
  File "f:\project\styletransfer\code\attempt\rsfnet\basicsr\ops\color\pyinterfaces.py", line 7, in <module>
    from cudaops_color import (rgb2lab_srgb_forward, rgb2lab_srgb_backward)
ModuleNotFoundError: No module named 'cudaops_color'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\project\StyleTransfer\code\attempt\RSFNet\basicsr\test.py", line 5, in <module>
    from basicsr.data import build_dataloader, build_dataset
  File "f:\project\styletransfer\code\attempt\rsfnet\basicsr\__init__.py", line 3, in <module>
    from .archs import *
  File "f:\project\styletransfer\code\attempt\rsfnet\basicsr\archs\__init__.py", line 16, in <module>
    _arch_modules = [importlib.import_module(f'basicsr.archs.{file_name}') for file_name in arch_filenames]
  File "f:\project\styletransfer\code\attempt\rsfnet\basicsr\archs\__init__.py", line 16, in <listcomp>
    _arch_modules = [importlib.import_module(f'basicsr.archs.{file_name}') for file_name in arch_filenames]
  File "C:\ProgramData\miniforge3\envs\bsr_rsf\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "f:\project\styletransfer\code\attempt\rsfnet\basicsr\archs\renderer_arch.py", line 10, in <module>
    from basicsr.ops.color import rgb2lab_func
  File "f:\project\styletransfer\code\attempt\rsfnet\basicsr\ops\color\__init__.py", line 1, in <module>
    from .pyinterfaces import rgb2lab_func, lab2rgb_func
  File "f:\project\styletransfer\code\attempt\rsfnet\basicsr\ops\color\pyinterfaces.py", line 10, in <module>
    cudaops_color = load(
  File "C:\ProgramData\miniforge3\envs\bsr_rsf\lib\site-packages\torch\utils\cpp_extension.py", line 1144, in load
    return _jit_compile(
  File "C:\ProgramData\miniforge3\envs\bsr_rsf\lib\site-packages\torch\utils\cpp_extension.py", line 1357, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\ProgramData\miniforge3\envs\bsr_rsf\lib\site-packages\torch\utils\cpp_extension.py", line 1469, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "C:\ProgramData\miniforge3\envs\bsr_rsf\lib\site-packages\torch\utils\cpp_extension.py", line 1717, in _run_ninja_build
    vc_env = distutils._msvccompiler._get_vc_env(plat_spec)
AttributeError: module 'distutils' has no attribute '_msvccompiler'
```

My platform is Win10, 4090Ti GUP. As the `REQUIRE` packages' version in setup.py is not compatible with my platform , I comment the line `install_requires(REQUIRE)` in setup.py and manually install the required packages.

**Comment by Vicky0522** [comment]
> @Vicky0522 So you mean I only need to run `python setup.py develop` in the root dir to build the basicsr package, and there is no need to build ops separately? I did in this way, and there is the output log:
> 
> ```
> (bsr_rsf) >python setup.py develop 
> running develop
> C:\ProgramData\miniforge3\envs\bsr_rsf\lib\site-packages\setuptools\command\develop.py:41: EasyInstallDeprecationWarning: easy_install command is deprecated.
> !!
> 
>         ********************************************************************************
>         Please avoid running ``setup.py`` and ``easy_install``.
>         Instead, use pypa/build, pypa/installer or other
>         standards-based tools.
> 
>         See https://github.com/pypa/setuptools/issues/917 for details.
>         ********************************************************************************
> 
> !!
>   easy_install.initialize_options(self)
> C:\ProgramData\miniforge3\envs\bsr_rsf\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
> !!
> 
>         ********************************************************************************
>         Please avoid running ``setup.py`` directly.
>         Instead, use pypa/build, pypa/installer or other
>         standards-based tools.
> 
>         See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
>         ********************************************************************************
> 
> !!
>   self.initialize_options()
> running egg_info
> writing basicsr.egg-info\PKG-INFO
> writing dependency_links to basicsr.egg-info\dependency_links.txt
> writing entry points to basicsr.egg-info\entry_points.txt
> writing requirements to basicsr.egg-info\requires.txt
> writing top-level names to basicsr.egg-info\top_level.txt
> reading manifest file 'basicsr.egg-info\SOURCES.txt'
> adding license file 'LICENSE'
> writing manifest file 'basicsr.egg-info\SOURCES.txt'
> running build_ext
> Creating c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages\basicsr.egg-link (link to .)
> Removing basicsr 1.2.0+63d5ab0 from easy-install.pth file
> basicsr 1.3.5 is already the active version in easy-install.pth
> detected new path 'f:\\project\\styletransfer\\code\\nafnet'
> Installing pyinstrument-script.py script to C:\ProgramData\miniforge3\envs\bsr_rsf\Scripts
> Installing pyinstrument.exe script to C:\ProgramData\miniforge3\envs\bsr_rsf\Scripts
> 
> Installed f:\project\styletransfer\code\attempt\rsfnet
> Processing dependencies for basicsr==1.3.5
> Searching for tensorboard==2.18.0
> Best match: tensorboard 2.18.0
> Adding tensorboard 2.18.0 to easy-install.pth file
> Installing tensorboard-script.py script to C:\ProgramData\miniforge3\envs\bsr_rsf\Scripts
> Installing tensorboard.exe script to C:\ProgramData\miniforge3\envs\bsr_rsf\Scripts
> 
> Using c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages
> Searching for werkzeug==3.0.6
> Best match: werkzeug 3.0.6
> Adding werkzeug 3.0.6 to easy-install.pth file
> 
> Using c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages
> Searching for tensorboard-data-server==0.7.2
> Best match: tensorboard-data-server 0.7.2
> Adding tensorboard-data-server 0.7.2 to easy-install.pth file
> 
> Using c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages
> Searching for six==1.16.0
> Best match: six 1.16.0
> Adding six 1.16.0 to easy-install.pth file
> 
> Using c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages
> Searching for setuptools==75.3.0
> Best match: setuptools 75.3.0
> Adding setuptools 75.3.0 to easy-install.pth file
> 
> Using c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages
> Searching for protobuf==4.25.5
> Best match: protobuf 4.25.5
> Adding protobuf 4.25.5 to easy-install.pth file
> 
> Using c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages
> Searching for packaging==24.1
> Best match: packaging 24.1
> Adding packaging 24.1 to easy-install.pth file
> 
> Using c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages\setuptools\_vendor
> Searching for numpy==1.26.0
> Best match: numpy 1.26.0
> Adding numpy 1.26.0 to easy-install.pth file
> Installing f2py-script.py script to C:\ProgramData\miniforge3\envs\bsr_rsf\Scripts
> Installing f2py.exe script to C:\ProgramData\miniforge3\envs\bsr_rsf\Scripts
> 
> Using c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages
> Searching for Markdown==3.7
> Best match: Markdown 3.7
> Adding Markdown 3.7 to easy-install.pth file
> Installing markdown_py-script.py script to C:\ProgramData\miniforge3\envs\bsr_rsf\Scripts
> Installing markdown_py.exe script to C:\ProgramData\miniforge3\envs\bsr_rsf\Scripts
> 
> Using c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages
> Searching for grpcio==1.67.1
> Best match: grpcio 1.67.1
> Adding grpcio 1.67.1 to easy-install.pth file
> 
> Using c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages
> Searching for absl-py==2.1.0
> Best match: absl-py 2.1.0
> Adding absl-py 2.1.0 to easy-install.pth file
> 
> Using c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages
> Searching for MarkupSafe==3.0.2
> Best match: MarkupSafe 3.0.2
> Adding MarkupSafe 3.0.2 to easy-install.pth file
> 
> Using c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages
> Searching for importlib-metadata==8.5.0
> Best match: importlib-metadata 8.5.0
> Adding importlib-metadata 8.5.0 to easy-install.pth file
> 
> Using c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages
> Searching for zipp==3.20.2
> Best match: zipp 3.20.2
> Adding zipp 3.20.2 to easy-install.pth file
> 
> Using c:\programdata\miniforge3\envs\bsr_rsf\lib\site-packages
> Finished processing dependencies for basicsr==1.3.5
> ```
> 
> Then, I run the test code:
> 
> ```
> >python basicsr/test.py -opt test_rsfnet_map_fivek_zas.yml
> Using C:\Users\mmm\AppData\Local\torch_extensions\torch_extensions\Cache\py39_cu113 as PyTorch extensions root...
> Detected CUDA files, patching ldflags
> Emitting ninja build file C:\Users\mmm\AppData\Local\torch_extensions\torch_extensions\Cache\py39_cu113\cudaops_color\build.ninja...
> Building extension module cudaops_color...
> Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
> Traceback (most recent call last):
>   File "f:\project\styletransfer\code\attempt\rsfnet\basicsr\ops\color\pyinterfaces.py", line 7, in <module>
>     from cudaops_color import (rgb2lab_srgb_forward, rgb2lab_srgb_backward)
> ModuleNotFoundError: No module named 'cudaops_color'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "F:\project\StyleTransfer\code\attempt\RSFNet\basicsr\test.py", line 5, in <module>
>     from basicsr.data import build_dataloader, build_dataset
>   File "f:\project\styletransfer\code\attempt\rsfnet\basicsr\__init__.py", line 3, in <module>
>     from .archs import *
>   File "f:\project\styletransfer\code\attempt\rsfnet\basicsr\archs\__init__.py", line 16, in <module>
>     _arch_modules = [importlib.import_module(f'basicsr.archs.{file_name}') for file_name in arch_filenames]
>   File "f:\project\styletransfer\code\attempt\rsfnet\basicsr\archs\__init__.py", line 16, in <listcomp>
>     _arch_modules = [importlib.import_module(f'basicsr.archs.{file_name}') for file_name in arch_filenames]
>   File "C:\ProgramData\miniforge3\envs\bsr_rsf\lib\importlib\__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "f:\project\styletransfer\code\attempt\rsfnet\basicsr\archs\renderer_arch.py", line 10, in <module>
>     from basicsr.ops.color import rgb2lab_func
>   File "f:\project\styletransfer\code\attempt\rsfnet\basicsr\ops\color\__init__.py", line 1, in <module>
>     from .pyinterfaces import rgb2lab_func, lab2rgb_func
>   File "f:\project\styletransfer\code\attempt\rsfnet\basicsr\ops\color\pyinterfaces.py", line 10, in <module>
>     cudaops_color = load(
>   File "C:\ProgramData\miniforge3\envs\bsr_rsf\lib\site-packages\torch\utils\cpp_extension.py", line 1144, in load
>     return _jit_compile(
>   File "C:\ProgramData\miniforge3\envs\bsr_rsf\lib\site-packages\torch\utils\cpp_extension.py", line 1357, in _jit_compile
>     _write_ninja_file_and_build_library(
>   File "C:\ProgramData\miniforge3\envs\bsr_rsf\lib\site-packages\torch\utils\cpp_extension.py", line 1469, in _write_ninja_file_and_build_library
>     _run_ninja_build(
>   File "C:\ProgramData\miniforge3\envs\bsr_rsf\lib\site-packages\torch\utils\cpp_extension.py", line 1717, in _run_ninja_build
>     vc_env = distutils._msvccompiler._get_vc_env(plat_spec)
> AttributeError: module 'distutils' has no attribute '_msvccompiler'
> ```
> 
> My platform is Win10, 4090Ti GUP. As the `REQUIRE` packages' version in setup.py is not compatible with my platform , I comment the line `install_requires(REQUIRE)` in setup.py and manually install the required packages.

The code in pyinterfaces.py will attempt to install the cudaops_color module if it is not already installed: [Link to the code](https://github.com/Vicky0522/RSFNet/blob/c1d6b2ec8c53916f441c310b2ca7d6047eaf0cdb/basicsr/ops/color/pyinterfaces.py#L6).

According to your error log, the actual cause of the error is:
`AttributeError: module 'distutils' has no attribute '_msvccompiler'`
This issue is likely related to the version of setuptools you are using. A similar problem has been discussed here for your reference: [PyTorch Issue #136541](https://github.com/pytorch/pytorch/issues/136541).

**Comment by dawnlh** [comment]
Thanks a lot for your quick reply. It's indeed caused by setuptools, and downgrading the version to 72.1.0 can solve the problem.
