### ISSUE TITLE
Training process is extremely slow

### ISSUE THREAD

**Issue by dawnlh** [Vicky0522/RSFNet#4]
Thanks for sharing the wonderful project.
 
I can run the test.py successfully, but when I run the training code, the estimated finishing time is extremely long. 

![image](https://github.com/user-attachments/assets/4d120e9c-d329-4414-8de2-ebbc281f08bb)

I found that there was a recurrent log with regard to ninja appearing during training, Not quite sure if it caused the extremely slow training problem. 

Look forward to your help, thank you a lot.

**Comment by Vicky0522** [comment]
The finishing time might be related to the total number of training epochs. Have you checked the time cost for a single iteration?

**Comment by dawnlh** [comment]
I didn't change the `total_iter: 1000000` in the config file.  After training the model for 3days, I validated that the finishing time shown in the log is correct. Not quite sure if the recurrent issue with regard to ninja shown in the log caused the slow training speed, have you met the issue before?

**Comment by Vicky0522** [comment]
I haven't encountered this issue before, but it seems unlikely that Ninja is the cause. The message "no work to do" suggests that Ninja isn't performing any actions. Additionally, once cudaops_color has been built, it won't be rebuilt. I'm not certain about the actual cause, but the training speed could also be influenced by the type of GPU you're using.

**Comment by dawnlh** [comment]
Got it, thanks for your patient explanation.
